version: '3.7'

services:
  web:
    image: 'video-query-api'
    container_name: 'video-query-api'
    build: .
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8001
    environment:
      - API_DEBUG=True
      - API_DB_HOST=db
      - API_DB_NAME='video-query'
      - API_DB_PASS=password
      - API_DB_PORT=5432
      - API_DB_USER=user
      - API_SECRET_KEY='some-key'
    depends_on:
      - db
  db:
    image: postgres:11.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # persist data beyond life of container
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB='video-query'
  nginx:
    build: ./nginx
    ports:
        - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
