# Generated by Django 2.0 on 2018-02-13 21:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('is_match', models.BooleanField(default=0)),
                ('reference_time', models.PositiveIntegerField(default=0)),
                ('user_match', models.NullBooleanField(default=None)),
            ],
            options={
                'db_table': 'match',
                'ordering': ('-score',),
            },
        ),
        migrations.CreateModel(
            name='ProcessState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'process_state',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('reference_time', models.TimeField(default='00:00:00')),
                ('max_matches_for_review', models.PositiveIntegerField(default=20)),
                ('query_notes', models.TextField(null=True)),
                ('reference_clip_image', models.ImageField(null=True, upload_to='')),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('current_match_criterion', models.FloatField(default=0.8)),
                ('current_weights', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('process_state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='queries.ProcessState')),
            ],
            options={
                'db_table': 'query',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1)),
                ('match_criterion', models.FloatField(default=0.8)),
                ('weights', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queries.Query')),
            ],
            options={
                'db_table': 'query_result',
            },
        ),
        migrations.CreateModel(
            name='SearchSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'search_set',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.PositiveIntegerField()),
                ('signature', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
            options={
                'db_table': 'signature',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('path', models.CharField(max_length=4096, null=True)),
                ('search_set', models.ManyToManyField(to='queries.SearchSet')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.AddField(
            model_name='signature',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queries.Video'),
        ),
        migrations.AddField(
            model_name='query',
            name='search_set_to_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queries.SearchSet'),
        ),
        migrations.AddField(
            model_name='query',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queries.Video'),
        ),
        migrations.AddField(
            model_name='match',
            name='query_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queries.QueryResult'),
        ),
        migrations.AddField(
            model_name='match',
            name='reference_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_video', to='queries.Video'),
        ),
    ]
