# Generated by Django 2.0 on 2017-12-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='query_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queries.QueryResult'),
        ),
    ]
