# Generated by Django 2.0 on 2017-12-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='reference_clip_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
