# Generated by Django 2.2.8 on 2020-01-01 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='dnn_stream',
            field=models.ForeignKey(help_text='DNN stream name from dnn_streams table signifying which of the streams in the multi-stream DNN this row belongs.', on_delete=django.db.models.deletion.CASCADE, to='queries.DnnStream', to_field='type'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='video_clip',
            field=models.ForeignKey(help_text='Id in the video_clips table for the clip corresponding to this row.', on_delete=django.db.models.deletion.CASCADE, to='queries.VideoClip'),
        ),
        migrations.AlterField(
            model_name='match',
            name='query_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.QueryResult'),
        ),
        migrations.AlterField(
            model_name='queryresult',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.Query'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='video',
            field=models.ForeignKey(help_text='Id in the video table for the video corresponding to this clip', on_delete=django.db.models.deletion.CASCADE, to='queries.Video'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bypass_onboarding', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ]
        ),
    ]
