# Generated by Django 2.0 on 2017-12-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_dataset',
            new_name='dataset',
        ),
    ]
