# Generated by Django 2.0 on 2017-12-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchArray',
            new_name='MatchedArray',
        ),
        migrations.RenameField(
            model_name='matchedarray',
            old_name='nearmatches',
            new_name='near_matches',
        ),
    ]
