# Generated by Django 2.0 on 2018-02-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='process_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='queries.ProcessState'),
        ),
    ]
