# Generated by Django 2.0 on 2018-01-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-score',)},
        ),
        migrations.AddField(
            model_name='match',
            name='reference_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
