# Generated by Django 2.0 on 2018-02-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='search_set',
            new_name='search_sets',
        ),
    ]
