# Generated by Django 2.0 on 2017-12-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20171213_1339'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchedarray',
            table='matched_array',
        ),
    ]
