# Generated by Django 2.0 on 2018-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20180116_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='match',
            name='user_match',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='query',
            name='process',
            field=models.BooleanField(default=1),
        ),
    ]
