# Generated by Django 2.0 on 2018-02-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20180213_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signature',
            new_name='Feature',
        ),
    ]
