# Generated by Django 2.0 on 2017-12-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20171219_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='dataset',
            new_name='dataset_id',
        ),
    ]
