# Generated by Django 2.2.8 on 2020-03-17 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_date_created_search_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dated_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
