# Generated by Django 2.0 on 2018-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_auto_20180214_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnnStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80, unique=True)),
                ('max_number_of_splits', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'dnn_streams',
            },
        ),
        migrations.RemoveField(
            model_name='feature',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='snippet',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='video',
        ),
    ]
