# Generated by Django 2.0 on 2018-02-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_auto_20180201_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='user_match',
            field=models.NullBooleanField(),
        ),
    ]
