# Generated by Django 2.0 on 2017-12-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_auto_20171220_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='dataset_id',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='dataset_id',
            new_name='dataset',
        ),
    ]
