# Generated by Django 2.0 on 2018-02-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_auto_20180215_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(default=10)),
                ('debug_video_uri', models.CharField(max_length=4096, null=True)),
                ('notes', models.TextField(null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queries.Video')),
            ],
            options={
                'db_table': 'video_clip',
            },
        ),
    ]
