# Generated by Django 2.0 on 2017-12-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_auto_20171220_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchedarray',
            old_name='query_name',
            new_name='query',
        ),
    ]
