# Generated by Django 2.0 on 2018-02-15 17:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_videoclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='dnn_spec_uri',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='dnn_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='queries.DnnStream'),
        ),
        migrations.AddField(
            model_name='feature',
            name='dnn_stream_split',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='video_clip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='queries.VideoClip'),
        ),
        migrations.AddField(
            model_name='feature',
            name='weights_uri',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterModelTable(
            name='feature',
            table='feature',
        ),
    ]
