# Generated by Django 2.0 on 2017-12-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_auto_20171220_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='queries.Dataset'),
        ),
    ]
